module.exports = (client, commandName, color) => {
	const embed = new client.embed()
		.setTitle('CPU Command Help')
		.setDescription('This command searches a list of real life CPUs and supplies you with technical information about them. This guide explains how to use this command properly.')
		.addField('Name Search', `Name Search is the easiest method to find a specific CPU. The syntax of name search is \`${commandName} [CPU name]\`. CPU name is text that can include spaces but not commas. This text is transformed into all lowercase letters and matched with lowercase CPU names. Matches are assigned a value based on how well they match the search, if at all. This formula is \`Search length / CPU name length\`. Name search is optional when at least 1 filter is present.`)
		.addField('Filters', `Filters are a method to narrow down a big list of CPUs. The syntax of filters is \`[Property] [Operator] [Value]\` where Property is one of "cores", "threads", "base", "boost", "price", "socket" or "tdp". Operator is one of <, >, =, ~. Value is an integer, decimal number or text (can contain numbers, e.g. LGA 1200). Filters must be separated with a comma \`,\` A comma must also be added after Name Search, between Name Search and the first Filter.`)
		.addField('Filters - Part 2', `If the Property is "socket", < and > are not allowed and ~ matches CPUs with sockets that start with the text part of Value (Substring of Value, starting at the first character and ending at the first number, or ending of string, whichever comes first) If the Operator is ~, matches' Property must be ±20% of Value. Price is always measured in USD. Boost and base clocks are always measured in GHz. If you want to filter by price or clock speed, enter only an integer or decimal number without any GHz or Dollar signs. For decimal numbers, use \`.\`, e.g. \`price = 249.99\` matches CPUS which's price is equal to 249.99 USD ($).`)
		.addField('Multiple Search', `Multiple Search is a way to receive a list of CPU names and choose the one you want to learn more about. Multiple Search is activated when you add \`-s\` to the end of the command. Multiple Search orders all matches by best matches first and responds with all or 200 best matches and attaches a number to each one. If Name Search is active, matches are ordered by the assigned value of how well they match the CPU's name. If Name Search is not active, matches are ordered alphabetically. You can choose your preferred CPU by sending a message with a valid number. A valid number is an integer within the constraints given by the bot.`)
		.addField('Multiple Search: List', 'This variation of Multiple Search works exactly like Multiple Search, except it does not require you to select and respond with a valid number from the list of CPUs. Multiple Search: List is activated when you add \`-sl\` to the end of the command, instead of \`-s\` which is used for Multiple Search. This variation provides a list of CPUs that match the filters and/or Name Search with the same rules as Multiple Search. The purpose of this variation is to make it possible to find out e.g. how many CPUs exist in a given category.')
		.setColor(color)
	return embed;
};